### ISSUE TITLE
Support magento 2.4.7

### ISSUE THREAD

**Issue by harbuzniak** [jetrails/magento2-varnish#67]
after upgrading Magento CE to version 2.4.7 I got an error during `setup:di:compile`:
`Fatal error:  Declaration of JetRails\Varnish\Model\Adminhtml\Generator::generateVcl($version) must be compatible with Magento\PageCache\Model\Varnish\VclGenerator::generateVcl($version, $inputFile = null) in /vendor/jetrails/magento2-varnish/Model/Adminhtml/Generator.php on line 42`

**Comment by null93** [comment]
@harbuzniak Sorry for the late reply, this issue somehow slipped through the cracks.

Thank you very much for reporting this. I have a fix on the way and should be available in 3.0.5 of the module. I will update this issue when the version is released.
